# Generated by Django 5.1.4 on 2024-12-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата оплаты"
            ),
        ),
    ]
