# Generated by Django 5.1.4 on 2025-01-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплаты"},
        ),
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка для оплаты.",
                max_length=400,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="ID сессии оплаты.",
                max_length=255,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
