# Generated by Django 5.1.4 on 2025-01-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_options_payments_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.FloatField(verbose_name="Сумма оплаты"),
        ),
    ]
