# Generated by Django 5.1.4 on 2025-01-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="States"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.FloatField(blank=True, null=True, verbose_name="Сумма оплаты"),
        ),
    ]
