# Generated by Django 5.1.4 on 2024-12-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="materials.course",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.TextField(
                blank=True,
                help_text="Добавьте ссылку на видео",
                null=True,
                verbose_name="video_link",
            ),
        ),
    ]
