# Generated by Django 5.1.4 on 2025-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=10000, verbose_name="price"),
        ),
    ]
